---
- hosts: all
  become: yes
  
  vars:
    vm_name: debian

  vars_prompt:
    - name: snapshot_name
      prompt: Snapshot's name
      default: fresh_install
    
  tasks:
    - name: Ensure snapshot exsists.
      block:
        - name: List snapshots.
          command: "virsh snapshot-list {{ vm_name }}"
          register: snapshot_list_cmd
          
        - name: Create snapshot.
          command: "virsh snapshot-create-as {{ vm_name }} --name {{ snapshot_name }} --atomic"

