---
- hosts: all
  become: yes

  vars:
    - desktop_interface: desktop0
    - desktop_interface_path: "/etc/network/interfaces.d/{{ desktop_interface }}"
      
  tasks:
  - name: Ensure QEMU is installed.
    package:
      name: qemu-kvm
      state: present
    notify:
      - Make sure USER is in QEMU group.

  - name: Ensure Libvirt is installed.
    package:
      name:
        - libvirt0
        - python3-libvirt
        - python3-lxml        
        - libvirt-dev
        - libvirt-clients
        - libvirt-daemon
        - libvirt-daemon-system
        - bridge-utils
      state: present
    notify:
      - Enable Libvirt.
      
  - name: Ensure Libvirt's default network is destroyed.
    community.libvirt.virt_net:
      name: default
      state: absent

  - name: Generate random MAC address for dummy interface.
    command: python3 -c 'import os; print(":".join(["{:02x}".format(x) for x in b"\02x" + os.urandom(5)]))'
    register: random_mac

  - debug:
      msg: "{{ random_mac }}"
    
  - name: Create dummy interface.
    template:
      src: "./desktop_interface"
      dest: "{{ desktop_interface_path }}"
    with_items: "{{ random_mac['stdout'] }}"
    
  - name: Restart networking.
    service:
      name: networking
      state: restarted
      enabled: true
      
  handlers:
  - name: Make sure USER is in QEMU group.
    user:
      name: "{{ ansible_user }}"
      append: true
      groups:
        - kvm
           
  - name: Enable Libvirt.
    service:
      name: libvirtd
      state: started
      enabled: true
     
